### ISSUE TITLE
Heroku build fails

### ISSUE THREAD

**Issue by TravisTheTechie** [linemanjs/heroku-buildpack-lineman#36]
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Lineman app detected
remote: Reusing previous heroku NPM build cache
remote: -----> Resolving engine versions
remote: 
remote:        WARNING: No version of Node.js specified in package.json, see:
remote:        https://devcenter.heroku.com/articles/nodejs-support#versions
remote: 
remote: /tmp/node-bootstrap_node-Z0E2/bin/node: error while loading shared libraries: libssl.so.0.9.8: cannot open shared object file: No such file or director
remote:  !     Requested engine node version  does not match available versions: 0.10.21 [who cares] ... 0.4.7 
remote: 
remote:  !     Push rejected, failed to compile Lineman app
```

**Comment by TravisTheTechie** [comment]
Okay, looking at the logs, looks like https://github.com/linemanjs/heroku-buildpack-lineman/issues/27#issuecomment-48114238 is the issue why the site isn't loading, regardless of what it says during `git push`.

**Comment by searls** [comment]
keep me posted on your progress debugging this, travis.


in the future (at least with @cabbagejs), i want to accomplish this with the official multipack + official php pack (for nginx) + a small little script we add on top.




managing this buildpack has been a nightmare

**Comment by TravisTheTechie** [comment]
Some googling suggests perhaps it's cedar-14 vs. cedar. However, Heroku is having some downtime currently, so I can't explore it any further.

**Comment by searls** [comment]
If anyone's interested in a fun weekend project, a clean break from this buildpack that goes the multi-pack route would be an AWESOME thing to behold

**Comment by TravisTheTechie** [comment]
And yep, changing to cedar vs. cedar-14 fixed it.

**Comment by searls** [comment]
For the next person who gets stuck on this, could you share the command needed to specify a cedar app at a particular version?

**Comment by TravisTheTechie** [comment]
`heroku stack:set cedar` then `git push heroku master` to have a new release on that stack. It defaults to cedar-14 now. I'm not sure how long that's been the case, I don't expect much longer than a couple months. Otherwise I would have noticed before.

**Comment by searls** [comment]
Oh, good. I was worried you were saying folks would need to target old cedar to work. Sounds like a couple cedars were just funky. That would explain the last couple of months of hard-to-repro issues.

**Comment by kvarga** [comment]
```Shell
remote:  !   Cedar-10 will reach end-of-life on November 4th, 2015.```

This will probably need to get solved in the next few months or so.
